#!/bin/sh
#
#SBATCH --job-name="Production_block_2_run_1"
#SBATCH --partition=genoa
#SBATCH --time=5-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=1

# use default memory ammount
##SBATCH --exclusive
##SBATCH --mem=0

#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=v.j.lagerweij@tudelft.nl
#SBATCH --constraint=scratch-node  # Creates scratch temp file system for user refer to with $TMPDIR

## SNELLIUS POWER USAGE TRACKING
#SBATCH --ear=on
#SBATCH --ear-policy=monitoring
#SBATCH --ear-verbose=1


module load 2023
module load foss/2023a HDF5/1.14.0-gompi-2023a

vasp_path=~/software/vasp/vasp.6.4.3/bin
export SLURM_MPI_TYPE=pmi2   # temporary fix on Snellius with PMIX error


# Start copying to compute node and time that activity
start1=$(date +%s)
echo "Starting to copy"
cp -r  $SLURM_SUBMIT_DIR /$TMPDIR/$SLURM_JOBID  # copy files over to tmp drive located at the node
cd /$TMPDIR/$SLURM_JOBID
rm slurm-${SLURM_JOBID}.out  # make sure to not have a slurm output file in the tmp drive as that write back to submit folder
stop1=$(date +%s)
echo "Copying done, simulation starting, time elapesd is $(($stop1-$start1)) seconds"
# End copying

# Start running main program and time that activity
start2=$(date +%s)
srun ${vasp_path}/vasp_gam  # run your main executable
stop2=$(date +%s)
echo "simulation done, copying starting, time elapesd is $(($stop2-$start2)) seconds"
# End running main program

# Start copying back to drive and time that activity
start3=$(date +%s)
rm -rf CHG CHGCAR DOSCAR EIGENVAL HILLSPOT IBZKPT ICONST PCDAT REPORT WAVECAR OUTCAR vasprun.xml  # delete unneeded files, which should not be communicated
rsync -a "$(pwd -P)/" ${SLURM_SUBMIT_DIR}  # when writing back to submit directory, rsync is the smarter solution
rm -rf /$TMPDIR/$SLURM_JOBID  # remove file to clean up after yourself
stop3=$(date +%s)
echo "Done with copying with rsync and files are removed, closing down job, time elapesd is $(($stop3-$start3)) seconds"
# End copying

